### ISSUE TITLE
Usage v-if or v-show inside template

### ISSUE THREAD

**Issue by ruslankonev** [JounQin/vue-dynamic#7] opened 2017-11-09 08:46 UTC
At first, — thanks for nice component, but in my use case, with dynamic changes in data props with `v-if` and `v-show` is not work in template. 

As example, on initial state of component I have an empty array named as `hideAgreements: []`. Inside dynamic component I render a list with v-for, and set up conditions to show items, based on his index:

```
<template v-for="(service,index) in services">
  <tr >
    <td :data="setAgreement(index, false)">{{index+1}}.</td>
    <td>....
      <span v-if="!getAgreement(index)" :class="`w-${getAgreement(index)}`">... {{agreement.name}} from {{agreement.startDate|date}}
          <span @click="setAgreement(index, !getAgreement(index))" class="no-print"> X</span>
    </td>
  </tr>
</template>
``` 
As you can see, I has a `@click`-event for change a state of `hideAgreement[index]`. In action — this these changes will occur inside the component scope, but render conditions `v-if` or `v-show` is not handled. 

What can work wrong?

**Comment by JounQin** [comment] 2017-11-09 09:04
Would you like to provide a minimize reproduction?

---

Besides, as I know Vue template can only contains one root children.

**Comment by ruslankonev** [comment] 2017-11-09 10:26
Of course, only one root. My template like a:
```
<div>
  <template v-for="(service,index) in services">
    <div>
      <span :data="setAgreement(index, false)">{{index+1}}.</span>
      <span>....
      <span v-if="!getAgreement(index)" :class="`w-${getAgreement(index)}`">... {{agreement.name}} from {{agreement.startDate}}
          <span @click="setAgreement(index, !getAgreement(index))" class="no-print"> X</span>
      </span>
    </div>
  </template>
</div>
```
Into `:comps` passed next data (`:comps="passedData"`):
```
passedData: [{
  template: `
<div>
  <template v-for="(service,index) in services">
    <div>
      <span :data="setAgreement(index, false)">{{index+1}}.</span>
      <span>....
      <span v-if="!getAgreement(index)" :class="`w-${getAgreement(index)}`">... {{agreement.name}} from {{agreement.startDate}}
          <span @click="setAgreement(index, !getAgreement(index))" class="no-print"> X</span>
      </span>
    </div>
  </template>
</div>
`,
  data: {
    hideAgreement: [],
    services: [{
      name: 'Service 1',
      startDate: '01.01.01'
    }, {
      name: 'Service 2',
      startDate: '02.02.02'
   }]
  },
  methods: {      
    setAgreement(idx, sett) {
      this.hideAgreement[idx] = sett
      console.log(this.getAgreement(idx))
    },
    getAgreement(idx){
      return this.hideAgreement[idx]
    }
  }
}]
```

**Comment by JounQin** [comment] 2017-11-09 13:32
@ruslankonev The problem is here: `this.hideAgreement[idx] = sett`

Vue can not detect array change in this way, you should use `this.$set(this.hideAgreement, idx, sett)`.

See: https://jsfiddle.net/z7w4o3fz/
Also: https://vuejs.org/v2/guide/list.html#Caveats

**Comment by JounQin** [comment] 2017-11-10 07:34
I'll close this issue for now, feel free to tell me if I'm wrong.

**Closed as completed by JounQin** 2017-11-10 07:34 UTC
