### ISSUE TITLE
Dynamic :comps working problem

### ISSUE THREAD

**Issue by tugrulugurlu** [JounQin/vue-dynamic#21] opened 2018-11-02 08:42 UTC
Hi @JounQin 

I am load dynamic companent to axios into another dynamic companent. 

I have a problem there.  :comps = "nestedView" declare in js that is ok but load time declare is not working

by example 

axios.get(....)
        .then(function (response) {
          page.view.NestedView = [{
                  template: '....',
                  data: {
                   ............................
                    }
            }];
        })

**Comment by JounQin** [comment] 2018-11-02 09:52
Your code sample is too simple to find out the problem.

**Comment by tugrulugurlu** [comment] 2018-11-02 10:54
Did you see this code work?

<template ref="entity">
  <div data-app>
    <dynamic :comps="views.mainView" :emptyView="emptyView"></dynamic>
  </div>
</template>

<script>
  import Vue from 'vue'
  import axios from "axios"

  const page = {
    views: {
      mainView: null,
      //nestedGuide: null, // NOT DECLARE FROM INITIAL DECLARE  AT RUNTIME IN VueDynamicNestedLoad()
    },
    emptyView: {
      template: '<p>No Item</p>',
    },
    mode: "Create",

    entityData: {},

    store: { },

    changeGuide(selectedGuide) {
      axios.get('/api/entity')
        .then(function (response) {
          VueDynamicNestedLoad("Guide", response);
        });
    }
  }

  window.page = page;

  export default {
    data() {
      return page
    }
  }

  function VueDynamicNestedLoad(nestedName, response) {
    Object.assign(page.store, response.data.enumBag);
    Object.assign(page.entityData, response.data.data);

    eval('page.views.nestedGuide = [{ template: response.data.template, data() { return page } }];'); 
    //nestedGuide DECLARE in EVAL()
  }

</script>

**Comment by JounQin** [comment] 2018-11-02 12:04
Can you please format your code by `prettier` or sth else and wrap it into a `code` block of markdown?

**Comment by tugrulugurlu** [comment] 2018-11-05 06:09
```html
<template ref="entity">
  <div data-app>
    <dynamic :comps="views.mainView" :emptyView="emptyView" ref="dynamic-panel"></dynamic>
  </div>
</template>
```

```javascript
  import Vue from 'vue'
  import axios from "axios"

  Vue.config.productionTip = false

  const page = {
    views: {
      mainView: null,
      //nestedGuide: null, // NOT DECLARE FROM INITIAL DECLARE  AT RUNTIME IN VueDynamicNestedLoad()
    },
    emptyView: {
      template: '<p>Runtime´da değiştirilen panel default değeri <br>Yeni ürün yaratmak için arama bölgesine n yazınız, a yazarak x ürününü görüntüleyebilir, b harfine basarak da y ürününü görüntüleyerek güncelleyebilirsiniz!</p>',
    },
    mode: "Create",

    entityData: {},

    store: {
    },

    changeGuide(selectedGuide) {
      axios.get('/api/entity', {
        params: {
          view: "Panel",
          type: selectedGuide,
          id: null,
          mode: page.mode,
          path: "Guide"
        }
      })
        .then(function (response) {
          VueDynamicNestedLoad("Guide", response);
        })
        .catch(function (error) {
          console.log(error);
        })
        .then(function () {

        });
    }
  }

  export default {
    data() {
      return page
    }
  }

  function VueDynamicNestedLoad(nestedName, response) {
    Object.assign(page.store, response.data.enumBag);
    Object.assign(page.entityData, response.data.data);

    eval('page.views.nested' + nestedName + ' = [{ template: response.data.template, data(){ return page } }];'); //nestedGuide DECLARE in EVAL() example page.views.nestedGuide = ...
  }
```

**Comment by JounQin** [comment] 2018-11-05 08:09
I don't see where are you changing `views.mainView` to execute rerendering.

And also, you can simply use `setTimeout` or `Promise` to simulate an API calling to provide a minimize reproduction, so that we can locate the issue quickly.

**Comment by tugrulugurlu** [comment] 2018-11-07 15:58
Hi @JounQin 

If you notice nestedGuide not declared in page.views. I am trying declare  in VueDynamicNestedLoad by eval. I use to v-radio-group(vuetify companent). v-radion trigger changeGuide method after and set template and data. But changeGuide not working properly first triggered. Second trigger is ok

```javascript
eval('page.views.nested' + nestedName + ' = [{ template: response.data.template, data(){ return page } }];');`

**Comment by JounQin** [comment] 2018-11-07 16:39
You really need to provide a runnable reproduction, because I really can not understand what you are trying to do: there is no `nestedGuide` usage in your template of example.

And also I don't understand why are you using `eval` instead of just calling

```js
page.views['nested' + nestedName] = [
  {
    template: response.data.template,
    data: page,
  },
]
```
which is much clearer.

**Comment by tugrulugurlu** [comment] 2018-11-14 13:26
Hi JounQin 

I solved my problem. new Vue.$set(objectName, propertyName, property) after added property reactive

**Comment by JounQin** [comment] 2018-11-14 13:47
OK, then I'll close this issue.

**Closed as completed by JounQin** 2018-11-14 13:47 UTC
